### ISSUE TITLE
PermissionError: Auth failed

### ISSUE THREAD

**Issue by leaf918** [barneygale/asyncvnc#7]
os :linux
app:xtightvnc.

![Uploading image.png…]()

**Comment by barneygale** [comment]
Fixed in 1.2.0.

**Comment by goodboy** [comment]
@barneygale fwiw i'm seeing this issue again with what i'm pretty sure is some new issue.

I'm using `x11vnc -passwd` and connecting manually with tigervnc works just fine.

I can make a new issue if you want?

**Comment by goodboy** [comment]
Yah, pretty confident this is still borked 😂 

I'm going to link to it from our code base.

**Comment by goodboy** [comment]
Yup, still to this day I can not use a pw and the connection is over a wg tunnel..

I can verify that `vncviewer host:port` works just fine with a `$VNC_PASSWORD` set.
