### ISSUE TITLE
Faster Screenshots?

### ISSUE THREAD

**Issue by victorhramos-dev** [barneygale/asyncvnc#8]
Is there anyway to take faster screenshots?

i was using vncdotool to handle with vnc servers but this time a need to to with concurrency.
waiting about 1 or 2 seconds to take a screenshot is really painful.

Is there any workaround to do this job faster?

**Comment by barneygale** [comment]
Can you share your code? Screenshots shouldn't be particularly slow!

**Comment by barneygale** [comment]
Ah right, I see that the example in the README was rather slow. I've released `asyncvnc==1.3.0` with a new `client.screenshot()` method that should be faster.

**However**, it will enter an infinite loop if you connect to a multi-head macOS server where the displays aren't perfectly aligned. Wrap it in `asyncio.wait_for()` if that's a concern.
